### ISSUE TITLE
This is more of a question then issue.

### ISSUE THREAD

**Issue by kzaher** [klundberg/Weakify#2]
This is same handy little code :), thnx.

Could it be extended so I can also write:

``` swift

func a(doIt: String -> Int) {
}

a(weakify(self) { `self`, input in 
     // .....
     return 1
})
```

?

**Comment by klundberg** [comment]
Sorry for the delay!

I'm not quite sure what you're trying to do here. Could you go into a little more detail as to what you're trying to do, with perhaps a code sample that compiles and runs today without weakify so that I can see what benefit it might bring?

**Comment by klundberg** [comment]
Closing for now until there's more info available.
